export const demoUser = {
  id: 'demo-user',
  email: 'demo',
  user_metadata: {},
  app_metadata: {},
}

export const demoItems = [
  {
    id: 'demo-item-1',
    code: '1001',
    description: 'Tampa Plástica Azul',
    color: 'Azul',
    cycle_seconds: 8,
    cavities: 4,
    padrao: 10,
    embalagem: 'Saco 20 unidades',
    part_weight_g: 12,
    unit_value: 4.55,
    resin: 'PP',
    unidade: 'UN',
    cliente: 'Cliente Demo',
    estoque_minimo: 30,
    item_type: 'produto_acabado',
  },
  {
    id: 'demo-item-2',
    code: '2002',
    description: 'Pino Plástico Branco',
    color: 'Branco',
    cycle_seconds: 4,
    cavities: 8,
    padrao: 20,
    embalagem: 'Caixa 100 unidades',
    part_weight_g: 6,
    unit_value: 1.15,
    resin: 'PA',
    unidade: 'UN',
    cliente: 'Cliente Demo',
    estoque_minimo: 50,
    item_type: 'insumo',
  },
  {
    id: 'demo-item-3',
    code: '3003',
    description: 'Flange PVC Cinza',
    color: 'Cinza',
    cycle_seconds: 12,
    cavities: 2,
    padrao: 6,
    embalagem: 'Pallet 60 peças',
    part_weight_g: 35,
    unit_value: 8.25,
    resin: 'PVC',
    unidade: 'UN',
    cliente: 'Cliente Demo',
    estoque_minimo: 20,
    item_type: 'produto_acabado',
  },
  {
    id: 'demo-item-4',
    code: '4004',
    description: 'Bucha Nylon 30mm',
    color: 'Natural',
    cycle_seconds: 10,
    cavities: 4,
    padrao: 15,
    embalagem: 'Saco 50 unidades',
    part_weight_g: 8,
    unit_value: 2.70,
    resin: 'PA',
    unidade: 'UN',
    cliente: 'Cliente Demo',
    estoque_minimo: 40,
    item_type: 'insumo',
  },
]

export const demoOrders = [
  {
    id: 'demo-order-01',
    company_id: null,
    machine_id: 'P1',
    code: 'OP-1001',
    customer: 'Cliente Demo',
    product: '1001 - Tampa Plástica Azul',
    color: 'Azul',
    qty: 240,
    boxes: 24,
    standard: '10',
    due_date: '2026-05-31',
    notes: 'Lançamento de produção demo para gráfico inicial.',
    status: 'PRODUZINDO',
    pos: 0,
    finalized: false,
    started_at: '2026-05-21T07:30:00.000Z',
    started_by: 'demo',
    scanned_count: 16,
  },
  {
    id: 'demo-order-02',
    company_id: null,
    machine_id: 'P2',
    code: 'OP-1002',
    customer: 'Cliente Demo',
    product: '2002 - Pino Plástico Branco',
    color: 'Branco',
    qty: 160,
    boxes: 8,
    standard: '20',
    due_date: '2026-06-01',
    notes: 'Ordem preparada para iniciar em breve.',
    status: 'AGUARDANDO',
    pos: 0,
    finalized: false,
    scanned_count: 0,
  },
  {
    id: 'demo-order-03',
    company_id: null,
    machine_id: 'P3',
    code: 'OP-1003',
    customer: 'Cliente Demo',
    product: '3003 - Flange PVC Cinza',
    color: 'Cinza',
    qty: 120,
    boxes: 20,
    standard: '6',
    due_date: '2026-05-30',
    notes: 'Ajuste de molde em andamento.',
    status: 'PARADA',
    pos: 0,
    finalized: false,
    started_at: '2026-05-21T08:10:00.000Z',
    started_by: 'demo',
    scanned_count: 10,
  },
  {
    id: 'demo-order-04',
    company_id: null,
    machine_id: 'P4',
    code: 'OP-1004',
    customer: 'Cliente Demo',
    product: '4004 - Bucha Nylon 30mm',
    color: 'Natural',
    qty: 150,
    boxes: 10,
    standard: '15',
    due_date: '2026-06-02',
    notes: 'Produção de segunda etapa.',
    status: 'AGUARDANDO',
    pos: 0,
    finalized: false,
    scanned_count: 0,
  },
]

export const demoStops = [
  {
    id: 'demo-stop-01',
    order_id: 'demo-order-03',
    machine_id: 'P3',
    reason: 'Ajuste de molde',
    notes: 'Revisar vazamento no molde antes de continuar.',
    started_at: '2026-05-21T09:12:00.000Z',
    resumed_at: null,
    company_id: null,
  },
]
